'use client';

import {FormEvent, useState} from 'react';
import {useTranslations} from 'next-intl';
import {useRouter} from '@/i18n/routing';
import {z} from 'zod';
import toast from 'react-hot-toast';
import {authService} from '@/services/api-service';
import {useAuth} from './auth-context';

export default function ProfilePanel() {
  const t = useTranslations('Profile');
  const router = useRouter();
  const [current, setCurrent] = useState(''); const [next, setNext] = useState(''); const [confirm, setConfirm] = useState(''); const [loading, setLoading] = useState(false); const {logout: clearSession} = useAuth();
  const submit = async (event: FormEvent) => {event.preventDefault(); const result = z.object({current: z.string().min(1, t('errors.required')), next: z.string().min(8, t('errors.short')), confirm: z.string().min(1, t('errors.required'))}).refine((data) => data.next === data.confirm, {path: ['confirm'], message: t('errors.mismatch')}).safeParse({current, next, confirm}); if (!result.success) {toast.error(result.error.issues[0]?.message ?? t('errors.generic')); return;} setLoading(true); try {await authService.changePassword(current, next); toast.success(t('success')); setCurrent(''); setNext(''); setConfirm('');} catch {toast.error(t('errors.generic'));} finally {setLoading(false);}};
  const logout = async () => {setLoading(true); try {await clearSession(); toast.success(t('logoutSuccess')); router.push('/');} catch {toast.error(t('errors.generic'));} finally {setLoading(false);}};
  return <main className="mx-auto min-h-screen max-w-4xl bg-background px-5 py-14 sm:px-8"><p className="text-[13px] font-bold uppercase tracking-[0.25em] text-primary">{t('eyebrow')}</p><h1 className="mt-3 text-4xl font-bold tracking-tight text-foreground sm:text-5xl">{t('title')}</h1><div className="mt-12 grid gap-8 lg:grid-cols-[1fr_1.5fr]"><section className="h-fit rounded-3xl border border-border bg-surface p-7 shadow-sm"><h2 className="text-xl font-bold text-foreground">{t('account.title')}</h2><p className="mt-4 text-[15px] leading-relaxed text-muted-foreground">{t('account.description')}</p><button type="button" disabled={loading} onClick={logout} className="mt-8 flex min-h-[52px] w-full items-center justify-center rounded-xl border border-rose-200 bg-rose-50/30 px-5 text-[15px] font-bold text-rose-600 transition-all hover:bg-rose-100 disabled:opacity-60">{loading ? t('loading') : t('logout')}</button></section><section className="rounded-3xl border border-border bg-surface p-7 shadow-sm"><h2 className="text-xl font-bold text-foreground">{t('change.title')}</h2><form onSubmit={submit} className="mt-6 space-y-6" noValidate>{[['current', current, setCurrent], ['next', next, setNext], ['confirm', confirm, setConfirm]].map(([key, value, setter]) => <label key={key as string} className="block text-[14px] font-bold text-foreground">{t(`fields.${key}`)}<input type="password" value={value as string} onChange={(event) => (setter as (value: string) => void)(event.target.value)} className="mt-2.5 min-h-[52px] w-full rounded-xl border border-border bg-background px-5 text-[15px] text-foreground outline-none transition-all focus:border-primary focus:ring-4 focus:ring-primary-subtle" /></label>)}<button type="submit" disabled={loading} className="mt-8 flex min-h-[56px] w-full items-center justify-center rounded-xl bg-primary text-[15px] font-bold text-white shadow-premium transition-all hover:bg-primary-hover hover:-translate-y-0.5 active:scale-95 disabled:cursor-not-allowed disabled:opacity-60">{loading ? t('loading') : t('change.submit')}</button></form></section></div></main>;
}
