import Image from 'next/image';
import {useTranslations} from 'next-intl';
import {Link} from '@/i18n/routing';
import ProductGrid from '@/components/store/product-grid';
import HeroCarousel from '@/components/store/hero-carousel';

const categoryCards = [
  {key: 'perfume', image: 'https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=700&q=88'},
  {key: 'skincare', image: 'https://images.unsplash.com/photo-1556229010-6c3f2c9ca5f8?auto=format&fit=crop&w=700&q=88'},
  {key: 'boutique', image: 'https://images.unsplash.com/photo-1445205170230-053b83016050?auto=format&fit=crop&w=700&q=88'},
  {key: 'wellness', image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=700&q=88'}
];

export default function Home() {
  const t = useTranslations('Storefront');
  return <main className="bg-background text-foreground">
    <section id="about" className="mx-auto grid max-w-7xl gap-8 px-5 pb-16 pt-6 sm:px-8 sm:pt-8 lg:grid-cols-[.92fr_1.08fr] lg:gap-12 lg:px-10 lg:pb-24 lg:pt-10">
      <div className="flex flex-col justify-center py-8 lg:py-16"><p className="mb-6 text-[13px] font-bold uppercase tracking-[0.25em] text-primary sm:text-sm">{t('hero.eyebrow')}</p><h1 className="max-w-xl whitespace-pre-line text-[clamp(2.8rem,6vw,5.75rem)] font-bold leading-[1.05] tracking-tight text-foreground">{t('hero.title')}</h1><p className="mt-7 max-w-md text-[17px] leading-relaxed text-muted-foreground sm:text-[19px]">{t('hero.description')}</p><div className="mt-10 flex flex-wrap items-center gap-6"><Link href="/shop" className="group inline-flex min-h-[52px] items-center gap-3 rounded-full bg-primary px-8 text-[15px] font-semibold text-white shadow-premium transition-all hover:bg-primary-hover hover:shadow-premium-hover hover:-translate-y-0.5">{t('hero.cta')}<span className="text-lg transition-transform group-hover:translate-x-1" aria-hidden="true">→</span></Link><Link href="/#categories" className="text-[15px] font-semibold text-foreground underline decoration-border underline-offset-8 transition-colors hover:text-primary hover:decoration-primary-subtle">{t('hero.secondary')}</Link></div></div>
      <div className="relative min-h-[440px] rounded-[2.5rem] bg-muted shadow-premium sm:min-h-[560px] lg:min-h-[680px]"><HeroCarousel /></div>
    </section>
    <section id="categories" className="mx-auto max-w-7xl px-5 py-16 sm:px-8 lg:px-10 lg:py-28"><div className="mb-10 flex items-end justify-between gap-5"><div><p className="mb-4 text-[13px] font-bold uppercase tracking-[0.25em] text-primary">{t('categories.eyebrow')}</p><h2 className="text-3xl font-bold tracking-tight sm:text-[40px]">{t('categories.title')}</h2></div><Link href="/#categories" className="hidden text-[15px] font-semibold text-muted-foreground transition-colors hover:text-primary sm:block">{t('categories.view')} <span aria-hidden="true">↗</span></Link></div><div className="grid grid-cols-2 gap-4 sm:grid-cols-4 sm:gap-6">{categoryCards.map((category) => <Link href="/#categories" key={category.key} className="group relative block overflow-hidden rounded-[2rem] bg-muted aspect-[4/5] sm:aspect-square lg:aspect-[3/4]"><Image src={category.image} alt={t(`categories.${category.key}`)} fill sizes="(max-width: 640px) 45vw, 23vw" className="object-cover transition-transform duration-1000 group-hover:scale-110" /><div className="absolute inset-0 bg-gradient-to-t from-black/80 via-black/20 to-transparent opacity-80 transition-opacity duration-500 group-hover:opacity-100" /><div className="absolute inset-0 flex flex-col justify-end p-5 sm:p-6 lg:p-8"><h3 className="translate-y-2 text-[18px] font-bold tracking-tight text-white transition-transform duration-500 group-hover:translate-y-0 sm:text-2xl">{t(`categories.${category.key}`)}</h3><p className="mt-2 flex items-center gap-2 text-[13px] font-semibold text-white/0 opacity-0 transition-all duration-500 group-hover:text-white/90 group-hover:opacity-100">Explore Collection <span aria-hidden="true" className="translate-x-[-10px] transition-transform duration-500 group-hover:translate-x-0">→</span></p></div></Link>)}</div><Link href="/#categories" className="mt-8 block text-center text-[15px] font-semibold text-muted-foreground sm:hidden">{t('categories.view')} <span aria-hidden="true">↗</span></Link></section>
    <section className="border-t border-border bg-surface"><div className="mx-auto max-w-7xl px-5 py-16 sm:px-8 lg:px-10 lg:py-28"><div className="mb-12 flex items-end justify-between gap-5"><div><p className="mb-4 text-[13px] font-bold uppercase tracking-[0.25em] text-primary">{t('trending.eyebrow')}</p><h2 className="text-3xl font-bold tracking-tight sm:text-[40px]">{t('trending.title')}</h2></div><Link href="/shop" className="text-[15px] font-semibold text-muted-foreground transition-colors hover:text-primary">{t('trending.viewAll')} <span aria-hidden="true">↗</span></Link></div><ProductGrid /></div></section>
  </main>;
}
