'use client';

import Image from 'next/image';
import {useMemo, useState} from 'react';
import {useTranslations} from 'next-intl';
import {Link} from '@/i18n/routing';
import {catalog} from './catalog';
import {useCart} from './cart-context';

type Filters = {category: string; scent: string; color: string; maxPrice: number};

function ProductCard({product}: {product: (typeof catalog)[number]}) {
  const t = useTranslations('Storefront');
  const {addItem} = useCart();
  return <article className="group"><div className="relative aspect-[4/5] overflow-hidden rounded-2xl bg-[#f1f2f6]"><Link href={`/products/${product.id}`}><Image src={product.image} alt={t(`products.${product.key}.name`)} fill sizes="(max-width: 640px) 45vw, (max-width: 1024px) 30vw, 23vw" className="object-cover transition duration-700 group-hover:scale-105" /></Link><button type="button" onClick={() => addItem(product.id)} className="absolute bottom-3 left-3 right-3 hidden min-h-11 items-center justify-center rounded-xl bg-white/95 text-xs font-semibold text-slate-900 shadow-lg backdrop-blur transition hover:bg-indigo-600 hover:text-white sm:flex sm:translate-y-2 sm:opacity-0 sm:group-hover:translate-y-0 sm:group-hover:opacity-100">{t('products.addToCart')}</button></div><div className="mt-4 flex items-start justify-between gap-2"><div><Link href={`/products/${product.id}`} className="text-sm font-semibold text-slate-900 hover:text-indigo-600 sm:text-[15px]">{t(`products.${product.key}.name`)}</Link><p className="mt-1 text-xs text-slate-500">{t(`products.${product.key}.category`)}</p></div><p className="text-sm font-semibold text-slate-900">${product.price}</p></div><button type="button" onClick={() => addItem(product.id)} className="mt-3 min-h-10 w-full rounded-xl border border-slate-200 text-xs font-semibold text-slate-700 transition hover:border-indigo-600 hover:bg-indigo-600 hover:text-white sm:hidden">{t('products.addToCart')}</button></article>;
}

function FilterContent({filters, setFilters}: {filters: Filters; setFilters: (filters: Filters) => void}) {
  const t = useTranslations('Storefront');
  const option = (field: keyof Filters, value: string) => setFilters({...filters, [field]: filters[field] === value ? '' : value});
  return <div className="space-y-8"><div><h3 className="text-sm font-semibold text-slate-900">{t('filters.category')}</h3><div className="mt-4 space-y-3">{['perfume', 'skincare', 'boutique', 'wellness'].map((key) => <label key={key} className="flex cursor-pointer items-center gap-3 text-sm text-slate-600"><input type="radio" name="category" checked={filters.category === key} onChange={() => option('category', key)} className="h-4 w-4 accent-indigo-600" />{t(`categories.${key}`)}</label>)}</div></div><div><div className="flex items-center justify-between"><h3 className="text-sm font-semibold text-slate-900">{t('filters.price')}</h3><span className="text-xs text-slate-500">$0 — ${filters.maxPrice}</span></div><input aria-label={t('filters.price')} type="range" min="0" max="120" step="1" value={filters.maxPrice} onChange={(e) => setFilters({...filters, maxPrice: Number(e.target.value)})} className="mt-5 w-full accent-indigo-600" /></div><div><h3 className="text-sm font-semibold text-slate-900">{t('filters.scent')}</h3><div className="mt-4 flex flex-wrap gap-2">{['woody', 'floral', 'fresh', 'spicy'].map((key) => <button type="button" key={key} onClick={() => option('scent', key)} className={`rounded-full border px-3 py-2 text-xs transition ${filters.scent === key ? 'border-indigo-600 bg-indigo-600 text-white' : 'border-slate-200 text-slate-600 hover:border-indigo-300'}`}>{t(`filters.options.${key}`)}</button>)}</div></div><div><h3 className="text-sm font-semibold text-slate-900">{t('filters.color')}</h3><div className="mt-4 flex flex-wrap gap-2">{['amber', 'cream', 'green', 'rose'].map((key) => <button type="button" key={key} onClick={() => option('color', key)} className={`rounded-full border px-3 py-2 text-xs transition ${filters.color === key ? 'border-indigo-600 bg-indigo-600 text-white' : 'border-slate-200 text-slate-600 hover:border-indigo-300'}`}>{t(`filters.options.${key}`)}</button>)}</div></div><button type="button" onClick={() => setFilters({category: '', scent: '', color: '', maxPrice: 120})} className="text-sm font-semibold text-indigo-600 hover:text-violet-600">{t('filters.clear')}</button></div>;
}

export default function ShopClient() {
  const t = useTranslations('Storefront');
  const [filters, setFilters] = useState<Filters>({category: '', scent: '', color: '', maxPrice: 120});
  const [sort, setSort] = useState('featured');
  const [mobileFilters, setMobileFilters] = useState(false);
  const visible = useMemo(() => [...catalog].filter((p) => (!filters.category || p.category === filters.category) && (!filters.scent || p.scent === filters.scent) && (!filters.color || p.color === filters.color) && p.price <= filters.maxPrice).sort((a, b) => sort === 'priceLow' ? a.price - b.price : sort === 'priceHigh' ? b.price - a.price : catalog.indexOf(a) - catalog.indexOf(b)), [filters, sort]);
  return <main className="bg-[#fafbff] text-slate-950"><div className="mx-auto max-w-7xl px-5 pb-24 pt-12 sm:px-8 lg:px-10 lg:pt-16"><div className="max-w-2xl"><p className="mb-3 text-xs font-semibold uppercase tracking-[0.25em] text-indigo-600">{t('shop.eyebrow')}</p><h1 className="text-4xl font-semibold tracking-[-0.06em] sm:text-6xl">{t('shop.title')}</h1><p className="mt-5 text-base leading-7 text-slate-500">{t('shop.description')}</p></div><div className="mt-12 flex items-center justify-between border-y border-slate-200 py-4"><p className="text-sm text-slate-500">{t('shop.results', {count: visible.length})}</p><label className="flex items-center gap-3 text-sm font-medium text-slate-700"><span className="hidden sm:inline">{t('sort.label')}</span><select value={sort} onChange={(e) => setSort(e.target.value)} className="rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm outline-none focus:border-indigo-500"><option value="featured">{t('sort.featured')}</option><option value="priceLow">{t('sort.priceLow')}</option><option value="priceHigh">{t('sort.priceHigh')}</option></select></label></div><div className="mt-8 grid gap-10 lg:grid-cols-[220px_1fr] xl:grid-cols-[250px_1fr]"><aside className="hidden lg:block"><div className="sticky top-28"><h2 className="mb-6 text-lg font-semibold">{t('filters.title')}</h2><FilterContent filters={filters} setFilters={setFilters} /></div></aside><div>{visible.length ? <div className="grid grid-cols-2 gap-x-4 gap-y-9 sm:gap-x-6 xl:grid-cols-3">{visible.map((product) => <ProductCard key={product.id} product={product} />)}</div> : <div className="rounded-2xl border border-dashed border-slate-300 bg-white p-12 text-center"><p className="text-sm text-slate-500">{t('shop.empty')}</p></div>}</div></div></div><button type="button" onClick={() => setMobileFilters(true)} className="fixed bottom-5 left-1/2 z-30 flex min-h-12 -translate-x-1/2 items-center gap-2 rounded-full bg-slate-950 px-5 text-sm font-semibold text-white shadow-2xl shadow-slate-950/25 lg:hidden">{t('filters.mobileButton')}<span aria-hidden="true">+</span></button>{mobileFilters && <div className="fixed inset-0 z-50 bg-slate-950/30 lg:hidden" onClick={() => setMobileFilters(false)}><div className="absolute inset-x-0 bottom-0 max-h-[85vh] overflow-y-auto rounded-t-[2rem] bg-white p-6 pb-10 shadow-2xl" onClick={(e) => e.stopPropagation()}><div className="mx-auto mb-6 h-1.5 w-12 rounded-full bg-slate-200" /><div className="mb-7 flex items-center justify-between"><h2 className="text-xl font-semibold">{t('filters.title')}</h2><button type="button" onClick={() => setMobileFilters(false)} className="text-sm font-semibold text-indigo-600">{t('filters.done')}</button></div><FilterContent filters={filters} setFilters={setFilters} /></div></div>}</main>;
}
