'use client';
import { useState } from 'react';
import toast from 'react-hot-toast';
import { adminDirectoryService, type AdminCategory } from '../../services/api-service';
export default function CategoryEditModal({ category, onClose, onSaved }: { category: AdminCategory; onClose: () => void; onSaved: (category: AdminCategory) => void }) {
  const [name, setName] = useState(category.name); const [slug, setSlug] = useState(category.slug); const [description, setDescription] = useState(category.description || ''); const [saving, setSaving] = useState(false);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (!name.trim()) return toast.error('Category name is required.'); setSaving(true); try { const result = await adminDirectoryService.updateCategory(category._id, { name: name.trim(), slug: slug.trim(), description }); toast.success('Category updated.'); onSaved(result.data); } catch (error) { toast.error(error instanceof Error ? error.message : 'Could not update category.'); } finally { setSaving(false); } };
  return <div className="fixed inset-0 z-50 flex items-end justify-center bg-slate-950/40 sm:items-center sm:p-5" role="dialog" aria-modal="true" aria-labelledby="edit-category-title"><form onSubmit={submit} className="w-full max-w-lg rounded-t-3xl bg-white p-5 shadow-2xl sm:rounded-3xl sm:p-7"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-primary">Catalog</p><h2 id="edit-category-title" className="mt-1 text-xl font-bold">Edit category</h2></div><button type="button" onClick={onClose} className="rounded-xl border border-border px-3 py-2 text-sm" aria-label="Close">×</button></div><div className="mt-6 grid gap-4"><label className="grid gap-2 text-sm font-semibold">Name<input value={name} onChange={e=>setName(e.target.value)} className="min-h-11 rounded-xl border border-border px-3 outline-none focus:border-primary" /></label><label className="grid gap-2 text-sm font-semibold">Slug<input value={slug} onChange={e=>setSlug(e.target.value)} className="min-h-11 rounded-xl border border-border px-3 outline-none focus:border-primary" /></label><label className="grid gap-2 text-sm font-semibold">Description<textarea value={description} onChange={e=>setDescription(e.target.value)} rows={3} className="rounded-xl border border-border p-3 outline-none focus:border-primary" /></label></div><div className="mt-6 flex flex-col-reverse gap-3 sm:flex-row sm:justify-end"><button type="button" onClick={onClose} className="min-h-11 rounded-xl border border-border px-5 text-sm font-bold">Cancel</button><button disabled={saving} className="min-h-11 rounded-xl bg-primary px-5 text-sm font-bold text-white disabled:opacity-60">{saving?'Saving…':'Save changes'}</button></div></form></div>;
}
