const express = require('express');
const cookieParser = require('cookie-parser');
const { authMiddleware, authorize } = require('../middlewares/authMiddleware');
const { getOverview } = require('../controllers/adminController');
const { listOrders, getOrder, updateStatus, updatePayment } = require('../controllers/adminOrderController');
const catalog = require('../controllers/adminCatalogController');
const customer = require('../controllers/adminCustomerController');
const moderation = require('../controllers/adminReviewCouponController');
const cms = require('../controllers/adminCmsController');
const settings = require('../controllers/adminSettingsController');
const auditLogger = require('../middlewares/auditLogger'); const audit = require('../controllers/auditLogController'); const refund = require('../controllers/adminRefundController');
const router = express.Router();
router.use(cookieParser(), authMiddleware, authorize('admin'));
router.use(auditLogger);
router.get('/overview', getOverview);
router.get('/orders', listOrders);
router.get('/orders/:id', getOrder);
router.put('/orders/:id/status', updateStatus);
router.put('/orders/:id/payment', updatePayment);
router.put('/orders/:id/refund', refund.refund);
router.get('/audit-logs', audit.list);
router.get('/products', catalog.listProducts); router.post('/products', catalog.createProduct); router.put('/products/:id', catalog.updateProduct); router.delete('/products/:id', catalog.archiveProduct);
router.get('/inventory', catalog.listInventory); router.put('/inventory/:id', catalog.updateInventory);
router.get('/categories', customer.listCategories); router.post('/categories', customer.createCategory); router.put('/categories/:id', customer.updateCategory); router.delete('/categories/:id', customer.deleteCategory);
router.get('/customers', customer.listCustomers); router.get('/customers/:id', customer.getCustomer); router.put('/customers/:id/status', customer.updateCustomerStatus);
router.get('/reviews', moderation.listReviews); router.put('/reviews/:id/status', moderation.reviewStatus); router.delete('/reviews/:id', moderation.deleteReview);
router.get('/coupons', moderation.listCoupons); router.post('/coupons', moderation.createCoupon); router.put('/coupons/:id', moderation.updateCoupon); router.delete('/coupons/:id', moderation.deleteCoupon);
router.get('/cms/homepage', cms.get); router.put('/cms/homepage', cms.update);
router.get('/settings', settings.get); router.put('/settings', settings.update);
router.get('/access', (req, res) => res.json({ success: true, data: { authorized: true, user: { id: req.user._id, firstName: req.user.firstName, lastName: req.user.lastName, email: req.user.email, role: req.user.role } } }));
module.exports = router;
