const express = require('express');
const cookieParser = require('cookie-parser');
const { authMiddleware, authorize } = require('../middlewares/authMiddleware');
const { getOverview } = require('../controllers/adminController');
const { listOrders, getOrder, updateStatus, updatePayment } = require('../controllers/adminOrderController');
const catalog = require('../controllers/adminCatalogController');
const customer = require('../controllers/adminCustomerController');
const router = express.Router();
router.use(cookieParser(), authMiddleware, authorize('admin'));
router.get('/overview', getOverview);
router.get('/orders', listOrders);
router.get('/orders/:id', getOrder);
router.put('/orders/:id/status', updateStatus);
router.put('/orders/:id/payment', updatePayment);
router.get('/products', catalog.listProducts); router.post('/products', catalog.createProduct); router.put('/products/:id', catalog.updateProduct); router.delete('/products/:id', catalog.archiveProduct);
router.get('/inventory', catalog.listInventory); router.put('/inventory/:id', catalog.updateInventory);
router.get('/categories', customer.listCategories); router.post('/categories', customer.createCategory); router.put('/categories/:id', customer.updateCategory); router.delete('/categories/:id', customer.deleteCategory);
router.get('/customers', customer.listCustomers); router.get('/customers/:id', customer.getCustomer);
router.get('/access', (req, res) => res.json({ success: true, data: { authorized: true, user: { id: req.user._id, firstName: req.user.firstName, lastName: req.user.lastName, email: req.user.email, role: req.user.role } } }));
module.exports = router;
