const express = require('express');
const cookieParser = require('cookie-parser');
const { authMiddleware, authorize } = require('../middlewares/authMiddleware');
const { getOverview } = require('../controllers/adminController');
const { listOrders, getOrder, updateStatus, updatePayment } = require('../controllers/adminOrderController');
const router = express.Router();
router.use(cookieParser(), authMiddleware, authorize('admin'));
router.get('/overview', getOverview);
router.get('/orders', listOrders);
router.get('/orders/:id', getOrder);
router.put('/orders/:id/status', updateStatus);
router.put('/orders/:id/payment', updatePayment);
router.get('/access', (req, res) => res.json({ success: true, data: { authorized: true, user: { id: req.user._id, firstName: req.user.firstName, lastName: req.user.lastName, email: req.user.email, role: req.user.role } } }));
module.exports = router;
