const crypto = require('crypto');
const Cart = require('../models/Cart');
const CartItem = require('../models/CartItem');
const Product = require('../models/Product');
const ProductVariant = require('../models/ProductVariant');
const Inventory = require('../models/Inventory');
const { AppError } = require('../middlewares/errorHandler');

const guestCookie = 'rc_cart_session';
const getCartKey = (req, res) => {
  if (req.user) return { user: req.user._id };
  const sessionId = req.cookies?.[guestCookie] || crypto.randomBytes(24).toString('hex');
  if (!req.cookies?.[guestCookie]) res.cookie(guestCookie, sessionId, { httpOnly: true, secure: process.env.NODE_ENV === 'production', sameSite: 'lax', maxAge: 30 * 86400000, path: '/api/cart' });
  return { sessionId };
};
const serialize = async (cart) => { const items = await CartItem.find({ cart: cart._id }).populate('product', 'name slug images').populate('variant', 'name sku size color price').lean(); return { id: cart._id, items: items.map((item) => ({ id: item._id, productId: item.product._id, variantId: item.variant?._id, quantity: item.quantity, price: item.unitPrice, name: item.productName, image: item.imageSnapshot || item.product.images?.[0], sku: item.sku })), subtotal: cart.subtotal, discount: cart.discount, shipping: cart.shipping, tax: cart.tax, total: cart.total, currency: cart.currency }; };
const findOrCreate = async (req, res) => { const key = getCartKey(req, res); return Cart.findOneAndUpdate({ ...key, status: 'active' }, { $setOnInsert: { ...key, status: 'active', currency: 'BDT' } }, { upsert: true, returnDocument: 'after', setDefaultsOnInsert: true }); };
const recalculate = async (cart) => { const items = await CartItem.find({ cart: cart._id }).lean(); cart.subtotal = items.reduce((sum, item) => sum + item.unitPrice * item.quantity, 0); cart.total = cart.subtotal - cart.discount + cart.shipping + cart.tax; await cart.save(); return cart; };

const getCart = async (req, res, next) => { try { const cart = await findOrCreate(req, res); return res.json({ success: true, data: await serialize(cart) }); } catch (error) { return next(error); } };
const addToCart = async (req, res, next) => { try { const { productId, variantId, quantity = 1 } = req.body; const amount = Number(quantity); if (!Number.isInteger(amount) || amount < 1) return next(new AppError('Quantity must be a positive integer.', 400, 'INVALID_QUANTITY')); const product = await Product.findOne({ _id: productId, status: 'active' }).lean(); if (!product) return next(new AppError('Product not found.', 404, 'PRODUCT_NOT_FOUND')); const variant = variantId ? await ProductVariant.findOne({ _id: variantId, product: product._id, isActive: true }).lean() : await ProductVariant.findOne({ product: product._id, isActive: true }).lean(); if (!variant) return next(new AppError('Product variant not found.', 404, 'VARIANT_NOT_FOUND')); const inventory = await Inventory.findOne({ variant: variant._id }).lean(); const available = inventory?.trackInventory === false ? Number.MAX_SAFE_INTEGER : Math.max(0, (inventory?.quantity || 0) - (inventory?.reservedQuantity || 0)); const cart = await findOrCreate(req, res); const item = await CartItem.findOne({ cart: cart._id, product: product._id, variant: variant._id }); const nextQuantity = (item?.quantity || 0) + amount; if (nextQuantity > available) return next(new AppError(`Only ${available} item(s) available.`, 409, 'INSUFFICIENT_STOCK')); if (item) { item.quantity = nextQuantity; item.unitPrice = variant.price; item.productName = product.name; item.sku = variant.sku; item.imageSnapshot = product.images?.[0]; await item.save(); } else await CartItem.create({ cart: cart._id, product: product._id, variant: variant._id, quantity: amount, unitPrice: variant.price, productName: product.name, sku: variant.sku, imageSnapshot: product.images?.[0] }); await recalculate(cart); return res.status(201).json({ success: true, data: await serialize(cart) }); } catch (error) { return next(error); } };
const updateCart = async (req, res, next) => { try { const { productId, variantId, quantity } = req.body; const amount = Number(quantity); const cart = await findOrCreate(req, res); const item = await CartItem.findOne({ cart: cart._id, product: productId, ...(variantId ? { variant: variantId } : {}) }); if (!item) return next(new AppError('Cart item not found.', 404, 'CART_ITEM_NOT_FOUND')); if (!Number.isInteger(amount) || amount < 1) { await item.deleteOne(); await recalculate(cart); return res.json({ success: true, data: await serialize(cart) }); } const inventory = await Inventory.findOne({ variant: item.variant }).lean(); const available = inventory?.trackInventory === false ? Number.MAX_SAFE_INTEGER : Math.max(0, (inventory?.quantity || 0) - (inventory?.reservedQuantity || 0)); if (amount > available) return next(new AppError(`Only ${available} item(s) available.`, 409, 'INSUFFICIENT_STOCK')); const variant = await ProductVariant.findById(item.variant).select('price').lean(); item.quantity = amount; item.unitPrice = variant?.price ?? item.unitPrice; await item.save(); await recalculate(cart); return res.json({ success: true, data: await serialize(cart) }); } catch (error) { return next(error); } };
const removeFromCart = async (req, res, next) => { try { const cart = await findOrCreate(req, res); await CartItem.deleteOne({ cart: cart._id, product: req.body.productId, ...(req.body.variantId ? { variant: req.body.variantId } : {}) }); await recalculate(cart); return res.json({ success: true, data: await serialize(cart) }); } catch (error) { return next(error); } };
module.exports = { getCart, addToCart, updateCart, removeFromCart };
