'use client';
import { FormEvent, useEffect, useState } from 'react';
import { useTranslations } from 'next-intl';
import { z } from 'zod';
import toast from 'react-hot-toast';
import { addressService, CustomerAddress } from '@/services/api-service';

export default function AccountAddresses() {
  const t = useTranslations('Account'); const [addresses, setAddresses] = useState<CustomerAddress[]>([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [form, setForm] = useState({ label: '', recipientName: '', phone: '', addressLine1: '', city: '', postalCode: '' });
  useEffect(() => { addressService.list().then((result) => setAddresses(result.data)).catch(() => toast.error(t('errors.generic'))).finally(() => setLoading(false)); }, [t]);
  async function save(event: FormEvent) { event.preventDefault(); const result = z.object({ label: z.string().trim().min(1, t('errors.required')), recipientName: z.string().trim().min(2, t('errors.required')), phone: z.string().trim().min(7, t('errors.phone')), addressLine1: z.string().trim().min(3, t('errors.required')), city: z.string().trim().min(2, t('errors.required')), postalCode: z.string().trim().min(3, t('errors.required')) }).safeParse(form); if (!result.success) { toast.error(result.error.issues[0].message); return; } setSaving(true); try { const response = await addressService.create({ ...form, type: 'shipping', country: 'Bangladesh' }); setAddresses((current) => [...current, response.data]); setForm({ label: '', recipientName: '', phone: '', addressLine1: '', city: '', postalCode: '' }); toast.success(t('addresses.saved')); } catch { toast.error(t('errors.generic')); } finally { setSaving(false); } }
  return <div className="space-y-8"><section className="rounded-2xl border border-slate-200 bg-white p-5 sm:p-7"><h2 className="text-xl font-semibold">{t('addresses.title')}</h2><p className="mt-2 text-sm text-slate-500">{t('addresses.description')}</p>{loading ? <div className="mt-7 h-20 animate-pulse rounded-xl bg-slate-100" /> : <div className="mt-7 grid gap-4 sm:grid-cols-2">{addresses.map((address) => <div key={address._id} className="rounded-xl border border-slate-200 p-4"><p className="text-sm font-semibold">{address.label}</p><p className="mt-2 text-sm leading-6 text-slate-500">{address.recipientName}<br />{address.addressLine1}<br />{address.city} · {address.postalCode}</p></div>)}</div>}</section><section className="rounded-2xl border border-slate-200 bg-white p-5 sm:p-7"><h2 className="text-xl font-semibold">{t('addresses.addTitle')}</h2><form onSubmit={save} className="mt-6 grid gap-5 sm:grid-cols-2" noValidate>{(['label', 'recipientName', 'phone', 'addressLine1', 'city', 'postalCode'] as const).map((key) => <label key={key} className={`block text-sm font-medium text-slate-700 ${key === 'addressLine1' ? 'sm:col-span-2' : ''}`}>{key === 'recipientName' ? t('profile.fields.firstName') : key === 'addressLine1' ? t('addresses.fields.line') : key === 'postalCode' ? t('addresses.fields.postal') : key === 'label' ? t('addresses.fields.label') : key === 'phone' ? t('profile.fields.phone') : t('addresses.fields.city')}<input value={form[key]} onChange={(event) => setForm({ ...form, [key]: event.target.value })} className="mt-2 min-h-12 w-full rounded-xl border border-slate-200 px-4 text-sm outline-none focus:border-indigo-500 focus:ring-4 focus:ring-indigo-100" /></label>)}<button type="submit" disabled={saving} className="min-h-12 rounded-xl bg-slate-950 px-6 text-sm font-semibold text-white disabled:opacity-60 sm:col-span-2 sm:w-fit">{saving ? t('loading') : t('addresses.save')}</button></form></section></div>;
}
