'use client';
import { FormEvent, useEffect, useState } from 'react';
import { useTranslations } from 'next-intl';
import { z } from 'zod';
import toast from 'react-hot-toast';
import { authService, userService } from '@/services/api-service';

export default function AccountProfile() {
  const t = useTranslations('Account'); const [profile, setProfile] = useState({ firstName: '', lastName: '', phone: '' }); const [password, setPassword] = useState({ current: '', next: '', confirm: '' }); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false);
  useEffect(() => { userService.profile().then(({ user }) => setProfile({ firstName: user.firstName, lastName: user.lastName, phone: user.phone || '' })).catch(() => toast.error(t('errors.generic'))).finally(() => setLoading(false)); }, [t]);
  const updateProfile = async (event: FormEvent) => { event.preventDefault(); const result = z.object({ firstName: z.string().trim().min(1, t('errors.required')), lastName: z.string().trim().min(1, t('errors.required')), phone: z.string().trim().min(7, t('errors.phone')) }).safeParse(profile); if (!result.success) { toast.error(result.error.issues[0].message); return; } setSaving(true); try { const response = await userService.updateProfile(profile); setProfile({ firstName: response.user.firstName, lastName: response.user.lastName, phone: response.user.phone || '' }); toast.success(t('profile.success')); } catch { toast.error(t('errors.generic')); } finally { setSaving(false); } };
  const changePassword = async (event: FormEvent) => { event.preventDefault(); const result = z.object({ current: z.string().min(1, t('errors.required')), next: z.string().min(8, t('errors.passwordShort')), confirm: z.string().min(1, t('errors.required')) }).refine((data) => data.next === data.confirm, { path: ['confirm'], message: t('errors.passwordMismatch') }).safeParse(password); if (!result.success) { toast.error(result.error.issues[0].message); return; } setSaving(true); try { await authService.changePassword(password.current, password.next); setPassword({ current: '', next: '', confirm: '' }); toast.success(t('password.success')); } catch { toast.error(t('errors.generic')); } finally { setSaving(false); } };
  if (loading) return <div className="flex min-h-40 items-center justify-center"><span className="h-6 w-6 animate-spin rounded-full border-2 border-indigo-200 border-t-indigo-600" /></div>;
  return <div className="space-y-8"><section className="rounded-2xl border border-slate-200 bg-white p-5 sm:p-7"><h2 className="text-xl font-semibold">{t('profile.title')}</h2><p className="mt-2 text-sm text-slate-500">{t('profile.description')}</p><form onSubmit={updateProfile} className="mt-7 grid gap-5 sm:grid-cols-2" noValidate>{(['firstName', 'lastName', 'phone'] as const).map((key) => <label key={key} className="block text-sm font-medium text-slate-700">{t(`profile.fields.${key}`)}<input value={profile[key]} onChange={(event) => setProfile({ ...profile, [key]: event.target.value })} className="mt-2 min-h-12 w-full rounded-xl border border-slate-200 px-4 text-sm outline-none focus:border-indigo-500 focus:ring-4 focus:ring-indigo-100" /></label>)}<button type="submit" disabled={saving} className="min-h-12 rounded-xl bg-slate-950 px-6 text-sm font-semibold text-white disabled:opacity-60 sm:col-span-2 sm:w-fit">{saving ? t('loading') : t('profile.submit')}</button></form></section><section className="rounded-2xl border border-slate-200 bg-white p-5 sm:p-7"><h2 className="text-xl font-semibold">{t('password.title')}</h2><form onSubmit={changePassword} className="mt-7 grid gap-5 sm:max-w-lg" noValidate>{(['current', 'next', 'confirm'] as const).map((key) => <label key={key} className="block text-sm font-medium text-slate-700">{t(`password.fields.${key}`)}<input value={password[key]} onChange={(event) => setPassword({ ...password, [key]: event.target.value })} type="password" className="mt-2 min-h-12 w-full rounded-xl border border-slate-200 px-4 text-sm outline-none focus:border-indigo-500 focus:ring-4 focus:ring-indigo-100" /></label>)}<button type="submit" disabled={saving} className="min-h-12 rounded-xl bg-slate-950 px-6 text-sm font-semibold text-white disabled:opacity-60 sm:w-fit">{saving ? t('loading') : t('password.submit')}</button></form></section></div>;
}
