'use client';

import {useEffect, useState} from 'react';
import {useTranslations} from 'next-intl';
import toast from 'react-hot-toast';
import {accountService} from '@/services/api-service';

type Order = {id: string; date: string; status: string; total: number; items: number};
export default function AccountOrders() { const t = useTranslations('Account'); const [orders, setOrders] = useState<Order[]>([]); const [loading, setLoading] = useState(true); const [selected, setSelected] = useState<string | null>(null); useEffect(() => {accountService.listOrders().then(setOrders).catch(() => toast.error(t('errors.generic'))).finally(() => setLoading(false));}, [t]); const statusClass = (status: string) => status === 'Delivered' ? 'bg-emerald-50 text-emerald-700' : status === 'Shipped' ? 'bg-indigo-50 text-indigo-700' : 'bg-amber-50 text-amber-700'; return <section className="rounded-2xl border border-slate-200 bg-white p-5 sm:p-7"><div className="flex items-center justify-between gap-4"><div><h2 className="text-xl font-semibold">{t('orders.title')}</h2><p className="mt-2 text-sm text-slate-500">{t('orders.description')}</p></div>{loading && <span className="h-5 w-5 animate-spin rounded-full border-2 border-indigo-200 border-t-indigo-600" />}</div>{!loading && <div className="mt-7 space-y-3">{orders.map((order) => <div key={order.id} className="rounded-xl border border-slate-200 p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm font-semibold">{order.id}</p><p className="mt-1 text-xs text-slate-500">{order.date} · {t('orders.items', {count: order.items})}</p></div><span className={`rounded-full px-3 py-1.5 text-xs font-semibold ${statusClass(order.status)}`}>{t(`orders.status.${order.status.toLowerCase()}`)}</span><p className="text-sm font-semibold">${order.total}</p><button type="button" onClick={() => {setSelected(selected === order.id ? null : order.id); toast.success(t('orders.viewed'));}} className="text-sm font-semibold text-indigo-600 hover:text-violet-600">{t('orders.view')}</button></div>{selected === order.id && <div className="mt-4 border-t border-slate-100 pt-4 text-sm leading-6 text-slate-500">{t('orders.detail', {id: order.id})}</div>}</div>)}</div>}</section>; }
