'use client';

import { useEffect, useState } from 'react';
import { usePathname } from 'next/navigation';
import { ErrorState, Skeleton } from './ui/primitives';

type Locale = 'en' | 'bn';
const copy = {
  en: { admin: 'Admin workspace', workspace: 'A calm view of your commerce.', operations: 'Operations', administrator: 'Administrator', unauthorized: 'You do not have administrator access.', open: 'Open navigation', close: 'Close navigation', language: 'Switch language', notifications: 'Notifications', user: 'Admin user', verifyError: 'Unable to verify administrator session.', nav: ['Overview', 'Orders', 'Payments', 'Products', 'Categories', 'Inventory', 'Customers', 'Reviews', 'Coupons & Promotions', 'Website CMS', 'Media Library', 'Analytics & Reports', 'Returns & Refunds', 'Notifications', 'Team & Roles', 'Settings', 'Audit Logs'] },
  bn: { admin: 'অ্যাডমিন ওয়ার্কস্পেস', workspace: 'আপনার কমার্স অপারেশনের শান্ত ভিউ।', operations: 'অপারেশনস', administrator: 'অ্যাডমিনিস্ট্রেটর', unauthorized: 'আপনার অ্যাডমিন অ্যাক্সেস নেই।', open: 'নেভিগেশন খুলুন', close: 'নেভিগেশন বন্ধ করুন', language: 'ভাষা পরিবর্তন করুন', notifications: 'নোটিফিকেশন', user: 'অ্যাডমিন ইউজার', verifyError: 'অ্যাডমিন সেশন যাচাই করা যায়নি।', nav: ['ওভারভিউ', 'অর্ডার', 'পেমেন্ট', 'পণ্য', 'ক্যাটাগরি', 'ইনভেন্টরি', 'কাস্টমার', 'রিভিউ', 'কুপন ও প্রমোশন', 'ওয়েবসাইট CMS', 'মিডিয়া লাইব্রেরি', 'অ্যানালিটিক্স ও রিপোর্ট', 'রিটার্ন ও রিফান্ড', 'নোটিফিকেশন', 'টিম ও রোল', 'সেটিংস', 'অডিট লগ'] },
} as const;
const icons = ['⌂', '↗', '◉', '◇', '◆', '▦', '◌', '☆', '%', '▣', '▤', '◒', '↩', '●', '♟', '⚙', '≡'];

export default function DashboardShell({ children }: { children: React.ReactNode }) {
  const [open, setOpen] = useState(false); const [locale, setLocale] = useState<Locale>('en'); const [access, setAccess] = useState<'loading' | 'allowed' | 'denied' | 'error'>('loading'); const pathname = usePathname(); const t = copy[locale];
  useEffect(() => { let active = true; const api = process.env.NEXT_PUBLIC_API_URL || '/api'; fetch(`${api}/admin/access`, { credentials: 'include' }).then((response) => { if (active) setAccess(response.ok ? 'allowed' : 'denied'); }).catch((err) => { if (active) setAccess(`error: ${err.message}` as any); }); return () => { active = false; }; }, []);
  if (access === 'loading') return <main className="flex min-h-screen items-center justify-center p-6"><Skeleton className="h-32 w-full max-w-xl" /></main>;
  if (access === 'denied') return <main className="flex min-h-screen items-center justify-center p-6"><ErrorState title={t.unauthorized} retry={() => window.location.reload()} /></main>;
  if (access.startsWith('error')) return <main className="flex min-h-screen items-center justify-center p-6"><ErrorState title={`${t.verifyError} (${access})`} retry={() => window.location.reload()} /></main>;
  return <div className="min-h-screen md:flex"><aside className={`${open ? 'translate-x-0' : '-translate-x-full'} fixed inset-y-0 left-0 z-40 w-72 overflow-y-auto border-r border-border bg-white/95 p-6 shadow-xl backdrop-blur-xl transition-transform md:static md:translate-x-0 md:shadow-none`}><div className="flex items-center gap-3 border-b border-border pb-7"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-foreground text-sm font-bold text-white">R</span><div><p className="font-bold">ReadyCommerce</p><p className="text-xs text-slate-500">{t.admin}</p></div></div><nav className="mt-8 space-y-1.5" aria-label={t.operations}>{t.nav.map((label, index) => <a href={index === 0 ? '/' : index === 1 ? '/orders' : `/#${label.toLowerCase().replaceAll(' ', '-')}`} key={label} onClick={() => setOpen(false)} className={`flex min-h-11 items-center gap-3 rounded-xl px-4 text-left text-sm font-semibold transition ${index === 0 && pathname === '/' ? 'bg-primary text-white shadow-sm' : 'text-slate-600 hover:bg-muted hover:text-foreground'}`}><span className="w-5 text-center text-xs" aria-hidden="true">{icons[index]}</span>{label}</a>)}</nav></aside>{open && <button type="button" aria-label={t.close} onClick={() => setOpen(false)} className="fixed inset-0 z-30 bg-slate-950/30 md:hidden" />}<div className="min-w-0 flex-1"><header className="flex min-h-20 items-center justify-between gap-4 border-b border-border bg-white/75 px-5 py-4 backdrop-blur-xl sm:px-8"><button type="button" aria-label={t.open} onClick={() => setOpen(true)} className="rounded-xl border border-border px-3 py-2 text-lg md:hidden">☰</button><div className="hidden md:block"><p className="text-xs font-bold uppercase tracking-[0.22em] text-primary">{t.operations}</p><p className="mt-1 text-sm text-slate-500">{t.workspace}</p></div><div className="ml-auto flex items-center gap-3"><button type="button" onClick={() => setLocale(locale === 'en' ? 'bn' : 'en')} className="rounded-full border border-border px-3 py-2 text-xs font-bold" aria-label={t.language}>{locale === 'en' ? 'BN' : 'EN'}</button><button type="button" aria-label={t.notifications} className="relative rounded-xl border border-border px-3 py-2 text-base">♢<span className="absolute right-1 top-1 h-1.5 w-1.5 rounded-full bg-primary" /></button><span className="hidden text-right sm:block"><span className="block text-sm font-bold">{t.user}</span><span className="block text-xs text-slate-500">{t.administrator}</span></span><span className="flex h-10 w-10 items-center justify-center rounded-full bg-primary/10 font-bold text-primary">A</span></div></header><main className="p-5 sm:p-8 lg:p-10">{children}</main></div></div>;
}
